---
- hosts: dev
  become: true

  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

  # Apache Configuration
    - name: Install HTTPD and PHP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'apache2' ]

  # Create html file and add content
    - name: Create html file with contents
      copy:
        dest: "/var/www/html/index.html"
        content: "This is a Nautilus sample file, created using Ansible!\n"
        owner: "www-data"
        group: "www-data"
        mode: '0655'

  # Update content in html file
    - name: Update content in html file
      lineinfile:
        path: /var/www/html/index.html
        line: 'Welcome to xFusionCorp Industries!'
        insertbefore: This*
